# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MustDo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'

  # Pods for MustDo

end
